/* eslint-disable */
// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/genSitePages.mjs

export type SitePage = {
  href: string;
  title: string;
  section?: string;
  labels?: string[];
  description?: string;
  keywords?: string[];
  excerpt?: string;
  content?: string;
};

export const SITE_PAGES: SitePage[] = [
  {
    "href": "/",
    "title": "Home",
    "section": "home",
    "labels": [
      "home"
    ],
    "description": "Sección: Home.",
    "excerpt": "Now Lo que está vivo ahora mismo (sin humo). Trabajos destacados. Aquí verás las últimas publicaciones. Si quieres pásate por el archivo para ver más. Tattoo, visuales, música, webapps o automatizaciones. Filmmaking Si quieres profundizar o colaborar en cualqu",
    "content": "Now Lo que está vivo ahora mismo (sin humo). Trabajos destacados. Aquí verás las últimas publicaciones. Si quieres pásate por el archivo para ver más. Tattoo, visuales, música, webapps o automatizaciones. Filmmaking Si quieres profundizar o colaborar en cualquiera de estos temas escríbeme y hablamos."
  },
  {
    "href": "/arte",
    "title": "Arte · elvasco.x",
    "section": "arte",
    "labels": [
      "art"
    ],
    "description": "Arte abstracto, fotografía, prints y proceso. Menos elementos, más intención: textura, ritmo y contraste.",
    "keywords": [
      "elvasco.x",
      "arte",
      "art",
      "arte abstracto",
      "abstract",
      "fotografía",
      "photography",
      "prints",
      "láminas",
      "proceso",
      "studio",
      "textura",
      "contraste",
      "blackwork mindset"
    ],
    "excerpt": "Si la pieza no respira, no es que falte algo: es que sobra.",
    "content": "Conexiones Arte · Photo — selección Tattoo, abstracto y fotografía: el mismo músculo con herramientas distintas. Primero una selección curada (editorial). Debajo: últimos 9, tal cual salen del taller. Encargos, prints, licencias, sesiones de foto/vídeo o piezas a medida. Si te vibra este universo: escríbeme. Arte abstracto, fotografía, prints y proceso. Menos elementos, más intención: textura, ritmo y contraste. “La obra no pide permiso. Pide espacio.” Lo abstracto no es un estilo: es un idioma. A veces la tinta dibuja, a veces la tinta confiesa. La foto no documenta: interpreta el pulso."
  },
  {
    "href": "/arte/galeria",
    "title": "Galería · Arte & Photo · elvasco.x",
    "section": "arte",
    "labels": [
      "art",
      "galeria"
    ],
    "description": "Galería de piezas, fotos y procesos. Filtra por intención: foto, láminas o proceso.",
    "keywords": [
      "elvasco.x",
      "galería",
      "galeria",
      "arte",
      "art",
      "fotografía",
      "fotografia",
      "photography",
      "prints",
      "láminas",
      "laminas",
      "proceso",
      "process",
      "abstract",
      "abstracto",
      "studio",
      "sketch",
      "canvas",
      "cuadro"
    ],
    "excerpt": "Galería · Arte & Photo Últimos publicados. Si hay cover, manda. Si no, a pelo. Encargos, prints, licencias, sesiones de foto/vídeo o piezas a medida. Si te vibra este universo: escríbeme. Galería de piezas, fotos y procesos. Filtra por intención: foto, láminas",
    "content": "Galería · Arte & Photo Últimos publicados. Si hay cover, manda. Si no, a pelo. Encargos, prints, licencias, sesiones de foto/vídeo o piezas a medida. Si te vibra este universo: escríbeme. Galería de piezas, fotos y procesos. Filtra por intención: foto, láminas o proceso."
  },
  {
    "href": "/bio",
    "title": "Bio · elvasco.x",
    "section": "bio",
    "labels": [
      "bio"
    ],
    "description": "Bio / manifiesto de El Vasco: tattoo, música, film y creative dev. Un archivo vivo: proceso, cicatrices y obra real.",
    "keywords": [
      "bio"
    ],
    "excerpt": "Bio / manifiesto de El Vasco: tattoo, música, film y creative dev. Un archivo vivo: proceso, cicatrices y obra real."
  },
  {
    "href": "/booking",
    "title": "Booking Tattoo · elvasco.x",
    "section": "booking",
    "labels": [
      "booking"
    ],
    "description": "Reserva tattoo con plantilla clara. Email o WhatsApp. Menos ida/vuelta: zona, tamaño, idea, referencias, fechas y presupuesto.",
    "keywords": [
      "booking"
    ],
    "excerpt": "Para agendar contigo necesito 1 minuto de info bien puesta. Si me mandas esto, te respondo rápido y sin ida/vuelta eterna."
  },
  {
    "href": "/contacto",
    "title": "Contacto · elvasco.x",
    "section": "contacto",
    "labels": [
      "contact"
    ],
    "description": "Contacto para tattoo, film, música o colaboraciones. Brief claro, respuesta honesta. Email, booking e Instagram DM.",
    "keywords": [
      "contacto"
    ],
    "excerpt": "Tattoo / Film / Música. Sin postureo: dime qué necesitas y te digo si encaja."
  },
  {
    "href": "/dev",
    "title": "Dev",
    "section": "dev",
    "labels": [
      "dev"
    ],
    "description": "Full Stack + AI + automatización. Herramientas, plataformas y pipelines: menos fricción, más obra.",
    "keywords": [
      "dev"
    ],
    "excerpt": "Velocidad con cabeza. Diseño con intención. Automatización sin perder control.",
    "content": "Qué construyo Web & Platforms Automations (n8n) AI workflows Stack GitHub Tres caminos. Un mismo objetivo: convertir ideas en sistemas que funcionan. Plataformas que no son escaparate: son archivo vivo, sistema editorial y motor de crecimiento. Aquí es donde se gana tiempo de verdad: flujos que convierten tareas repetidas en sistema. IA aplicada, sin fantasía: conectada a herramientas, con reglas, y con salida utilizable. Herramientas que uso de verdad. Lo importante es el ojo y el sistema. Preview rápida (manual). Luego lo conectamos con API cuando quieras. Webs, apps internas, automatizaciones (n8n), pipelines de contenido o IA aplicada. Si quieres algo útil y bien hecho: hablamos. “Si se puede automatizar, no merece repetirse.” El dev para mí es oficio: convertir caos en estructura. Lo mismo que hago con negros y composición, pero en software. Y sí: n8n es mi martillo favorito."
  },
  {
    "href": "/film",
    "title": "Film · elvasco.x",
    "section": "film",
    "labels": [
      "film"
    ],
    "description": "Filmmaking, videoclips, documentales, edición, VFX y color grading. Crudo y cuidado: ritmo, textura y verdad.",
    "keywords": [
      "elvasco.x",
      "film",
      "filmmaking",
      "videoclip",
      "documental",
      "edición",
      "montaje",
      "VFX",
      "compositing",
      "motion graphics",
      "color grading",
      "DaVinci Resolve",
      "After Effects"
    ],
    "excerpt": "La historia manda. El look acompaña. El montaje decide.",
    "content": "Inicios Videoclips Lyric videos VFX Color grading Tool stack Cómo entré en el audiovisual y por qué me quedé en el filmmaking. Concepto simple, ejecución sólida, montaje al servicio del tema. Tipografía y ritmo: cuando la letra también es un instrumento. Plano limpio, audio cuidado, montaje con respeto. Integración primero, brillo después. Look con intención: contraste, piel y negros que respiran. Programas que uso y domino según el tipo de proyecto. Una muestra rápida. Si te interesa, te mando al canal. Videoclips, visuales, piezas documentales, edición, VFX o color. Si quieres algo crudo y bien hecho: hablamos. Filmmaking, videoclips, documentales, edición, VFX y color grading. Crudo y cuidado: ritmo, textura y verdad. “No grabo para enseñar. Grabo para que se sienta.” Me obsesiona el equilibrio: crudeza y cuidado. Un plano puede ser sucio y aún así estar bien hecho. Si la imagen no respira, da igual lo caro del equipo."
  },
  {
    "href": "/journal",
    "title": "Journal",
    "section": "journal",
    "labels": [
      "journal"
    ],
    "description": "Reflexiones, proceso, filosofía práctica y vida. Notas sin filtro desde el archivo de elvasco.x.",
    "keywords": [
      "journal"
    ],
    "excerpt": "Reflexiones, filosofía práctica, construcción, errores y aprendizajes. Sin filtro.",
    "content": "Journal · elvasco.x Reflexiones, proceso, filosofía práctica y vida. Notas sin filtro desde el archivo de elvasco.x."
  },
  {
    "href": "/musica",
    "title": "Música · elvasco.x",
    "section": "musica",
    "labels": [
      "music"
    ],
    "description": "Techno/electrónica y metal: ritmo, textura, tensión real. Lives, tracks, procesos y studio reports sin postureo.",
    "keywords": [
      "elvasco.x",
      "música",
      "techno",
      "electrónica",
      "acid",
      "liveset",
      "metal",
      "producción musical",
      "hardware",
      "studio report"
    ],
    "excerpt": "Hardware, improvisación y obsesión por el groove. “No computer” como disciplina, no como religión.",
    "content": "Elige camino Dos mundos Highlights Entrar por la puerta correcta importa. Si te metes por la equivocada… te pierdes (o te encuentras). Lo mismo, con dos idiomas. Uno te hipnotiza. El otro te despierta a hostias. Tres migas para que veas que esto está vivo. Lo gordo está dentro. Colaboraciones, lives, visuales y música para piezas o contenido. Si te mola lo crudo y lo bien hecho: hablamos. Techno/electrónica y metal: ritmo, textura, tensión real. Lives, tracks, procesos y studio reports sin postureo. “La música es un tatuaje en el aire: patrón, golpe, cicatriz.” Me interesa cuando suena a verdad: transitorios, saturación, respiración y decisión. En techno: trance. En metal: puño y disciplina. En ambos: carácter."
  },
  {
    "href": "/musica/metal",
    "title": "Thybreath - (Welcome to my Hell) All my Hate (Official video)",
    "section": "musica",
    "labels": [
      "music",
      "metal"
    ],
    "description": "Archivo vivo: historia personal (guitarra, voz, bajo), discografía, vídeos y galería.",
    "keywords": [
      "musica",
      "metal"
    ],
    "excerpt": "Esta página no pretende ser “promo”. Es un archivo: etapas, bandas, discos y aprendizajes. Si alguien encuentra aquí una referencia o un reflejo, perfecto. Si no, también: el metal ya cumplió su trabajo.",
    "content": "Historia Discografía Vídeos Metal archive (placeholder) Tres etapas: guitarra → voz → bajo. La misma pulsión, distinta herramienta. Discos y etapas. Portadas como entrada rápida; detalles tipo “bio documental” si te apetece bajar al barro. Playthroughs, directos, backstage. Pocas piezas, bien elegidas. Archivo visual. Una sola mosaic, sin convertir esto en un carrusel infinito. Si quieres hablar de música, colaborar o rescatar material antiguo con sentido, aquí estoy. Sin postureo: ideas claras. “El metal fue escuela: disciplina, rabia y método.” Hoy mi foco está en otros frentes, pero el metal fue la base: aprender a repetir hasta que salga, a tocar con intención y a respetar el silencio entre golpes. history-inicios Inicios chispa · primeras bandas history-guitarra Guitarra riffs & disciplina history-voz Voz frontal · intención history-bajo Bajo peso · groove"
  },
  {
    "href": "/musica/techno",
    "title": "Techno & Electrónica · elvasco.x",
    "section": "musica",
    "labels": [
      "music",
      "techno"
    ],
    "description": "Techno, electrónica y acid desde el hardware y la improvisación. Live sets, tracks, experiments y proceso real sin postureo.",
    "keywords": [
      "elvasco.x",
      "techno",
      "electrónica",
      "electronica",
      "acid",
      "303",
      "liveset",
      "live set",
      "hardware",
      "no computer",
      "improvisación",
      "studio report",
      "underground"
    ],
    "excerpt": "Si el loop no aguanta 8 minutos, no es el loop: es la intención.",
    "content": "Techno & Electrónica Live sets Sound experiments Samplepacks Cómo llegué a la electrónica y por qué elijo lo analógico y la improvisación. Singles y jams. Lo primero que entra aquí es lo más reciente. Directos y jams. Si te interesa cómo se decide, aquí está el backstage real. Notas, pruebas y resultados. Un laboratorio (sin bata). Próximamente. Sonidos reales, grabados y procesados en el mundo elvasco.x. Colaboraciones, lives, visuales, o música para piezas y contenido. Si te mola lo crudo y lo bien hecho: hablamos. Techno, electrónica y acid desde el hardware y la improvisación. Live sets, tracks, experiments y proceso real sin postureo. “Analog sound. No computer. Manos en la máquina.” La electrónica me gusta cuando suena a cuerpo: transitorios, saturación, tensión real. Improvisar no es tocar sin pensar: es pensar en tiempo real."
  },
  {
    "href": "/musica/techno/tracks",
    "title": "Techno Tracks Archive · elvasco.x",
    "section": "musica",
    "labels": [
      "music",
      "techno",
      "tracks"
    ],
    "description": "Archivo curado de tracks techno: canciones sueltas, bocetos que sobrevivieron y piezas terminadas. Sin relleno.",
    "keywords": [
      "elvasco.x",
      "techno",
      "tracks",
      "archivo",
      "electrónica",
      "electronica",
      "acid",
      "303",
      "hardware",
      "no computer",
      "underground",
      "spotify",
      "youtube",
      "bandcamp",
      "soundcloud"
    ],
    "excerpt": "Canciones sueltas, bocetos que sobrevivieron y piezas terminadas. Archivo curado. Sin relleno.",
    "content": "Techno Tracks Archive Archivo curado de tracks techno: canciones sueltas, bocetos que sobrevivieron y piezas terminadas. Sin relleno."
  },
  {
    "href": "/search",
    "title": "Search",
    "section": "search",
    "labels": [
      "search"
    ],
    "description": "Sección: Search.",
    "keywords": [
      "search"
    ],
    "excerpt": "Prueba con tags, estilos, bandas, técnicas, localizaciones… lo que te salga."
  },
  {
    "href": "/tattoo",
    "title": "Tattoo",
    "section": "tattoo",
    "labels": [
      "tattoo"
    ],
    "description": "Blackwork orgánico, blackout, op art/patrones y cultura del oficio. Técnica, composición y proceso real: diseño, sesión y curación.",
    "keywords": [
      "tattoo",
      "tatuaje",
      "blackwork",
      "blackout",
      "blackwork orgánico",
      "op art",
      "patrones",
      "geometría",
      "composición",
      "curación",
      "oficio",
      "elvasco.x"
    ],
    "excerpt": "Por eso insisto en proceso y curación. Un tatuaje no termina cuando se apaga la máquina. Termina cuando la piel lo integra. Ahí es donde se nota quién trabaja con método… y quién solo busca el aplauso rápido.",
    "content": "Tattoo · elvasco.x Elige un camino Mi enfoque Studio report Cuatro puertas. Dentro está el detalle: proceso, referencias, curación y trabajos. Una visión general. Vídeos cortos para ver el backstage: decisiones, proceso y realidad del oficio. Si te cuadra este enfoque (proceso, intención y curación bien hecha), hablamos. Los proyectos grandes se construyen con calma. Blackwork orgánico, blackout, op art/patrones y cultura del oficio. Técnica, composición y proceso real: diseño, sesión y curación."
  },
  {
    "href": "/tattoo/blackout",
    "title": "Blackout",
    "section": "tattoo",
    "labels": [
      "tattoo",
      "blackout"
    ],
    "description": "Sección: Blackout.",
    "keywords": [
      "tattoo",
      "blackout"
    ],
    "excerpt": "Qué es para mí el blackout NEOTRIBAL Proceso Recomendaciones Curación y cuidados Blackout Esto no es un texto largo: es un ensayo visual. Párrafos cortos, aire, y media intercalada. Un espacio aparte. Mis reglas, mi lectura, y por qué me interesa cuando se hac",
    "content": "Qué es para mí el blackout NEOTRIBAL Proceso Recomendaciones Curación y cuidados Blackout Esto no es un texto largo: es un ensayo visual. Párrafos cortos, aire, y media intercalada. Un espacio aparte. Mis reglas, mi lectura, y por qué me interesa cuando se hace con intención. Tres pasos, claros y visuales: diseño, sesión y curación. Negro grande = cuerpo trabajando. Aquí lo importante, sin paja. Esta sección es funcional: la uso para redirigirte después del tattoo. Mejor clara que poética. Mosaic elegante: B/N por defecto, dos acentos en rojo. Hover revela el color original. Click abre visor. Si quieres blackout, ven con intención y con tiempo. Lo demás lo afinamos juntos. Te dejo dos listas: preparación previa y durante la sesión. Ir a Booking Si algo te preocupa Dolor excesivo, calor raro, pus, mal olor, fiebre que no baja o enrojecimiento que se expande: me escribes. Prefiero que me des la turra a que te hagas el héroe. El tatuaje más anti-tatuaje. Descansar bien la noche anterior Comer una comida completa antes de la sesión Hidratar la piel los días previos Evitar alcohol y drogas 24h antes Usar ropa cómoda y adecuada Ropa cómoda pensando en la zona Mantener comunicación constante Tomar descansos cuando sea necesario Mantener niveles de azúcar estables Respirar profundo, relajarse y confiar en el proceso"
  },
  {
    "href": "/tattoo/blackwork-organic-abstract",
    "title": "Blackwork Organic Abstract",
    "section": "tattoo",
    "labels": [
      "tattoo",
      "blackwork-organic-abstract",
      "blackwork",
      "organic",
      "abstract"
    ],
    "description": "Sección: Blackwork Organic Abstract.",
    "keywords": [
      "tattoo",
      "blackwork",
      "organic",
      "abstract"
    ],
    "excerpt": "Trabajo pensando en anatomía y en lectura: dirección muscular, tensiones, curvas, zonas de descanso. El cuerpo no es un lienzo plano. Si el tatuaje no acompaña el movimiento, se muere.",
    "content": "Cómo entiendo el abstract organic blackwork Texturas Proceso Recomendaciones Curación y cuidados Abstract Organic Blackwork No se trata de rellenar. Se trata de leer. Arriba textura, abajo traducción a piel. Alternamos izquierda/derecha para que la página tenga ritmo. Tres pasos, claros. Sin humo. Trabajo grande = cuerpo trabajando. Esto te ayuda a llegar fino a la sesión y curar mejor. Práctico, claro y directo. Vuelves aquí después del tattoo. Mosaic elegante: B/N por defecto, dos acentos en rojo. Hover revela el color original. Click abre visor. Si quieres abstract organic blackwork, ven con intención y con tiempo. Lo demás lo afinamos juntos. Dos listas rápidas. Lo justo y necesario. Ir a Booking Si algo te preocupa Dolor excesivo, calor raro, pus, mal olor, fiebre que no baja o enrojecimiento que se expande: me escribes. Prefiero que me des la turra a que te hagas el héroe. “La naturaleza no dibuja limpio. Dibuja vivo.” Aquí no busco decorar: busco traducir textura real a un cuerpo real. Que se lea de lejos y que tenga piel de cerca. Dormir bien la noche anterior Comer una comida completa antes de venir Hidratar la piel los días previos Evitar alcohol y drogas 24h antes Ropa cómoda y adecuada para la zona Comunicación constante (si algo no va bien, se dice) Pausas cuando lo necesites (esto no es una prueba de ego) Mantener azúcar estable (trae algo si eres de bajones) Respirar y relajar hombros/mandíbula Confiar en el proceso artístico"
  },
  {
    "href": "/tattoo/op-art-pattern-abstraction",
    "title": "Op Art Pattern Abstraction",
    "section": "tattoo",
    "labels": [
      "tattoo",
      "op-art-pattern-abstraction",
      "op",
      "art",
      "pattern",
      "abstraction"
    ],
    "description": "Sección: Op Art Pattern Abstraction.",
    "keywords": [
      "tattoo",
      "op",
      "art",
      "pattern",
      "abstraction"
    ],
    "excerpt": "No son ilustraciones: son sistemas visuales. Reglas, variación y lectura. Si el patrón no se adapta a la anatomía, se convierte en estampado. Aquí manda el cuerpo."
  },
  {
    "href": "/tattoo/science",
    "title": "Custom BLACK-OUT coil machine",
    "section": "tattoo",
    "labels": [
      "tattoo",
      "science"
    ],
    "description": "Notas de taller sobre historia del tatuaje, máquinas de bobina, soldado de agujas y experimentos prácticos.",
    "keywords": [
      "tattoo",
      "science"
    ],
    "excerpt": "Si lo miras con calma, hay un patrón: cuando el tatuaje se vuelve “moda”, el oficio se protege volviendo a lo esencial. Menos prisa. Más método. Más respeto por la piel como órgano vivo.",
    "content": "History Coil machines Needle soldering Tattoo experiments Un recorrido largo: el tatuaje como marca cultural, tecnología y lenguaje del cuerpo. Por qué me gusta la tradición: bobinas, golpe, sonido y control. Soldar agujas: libertad creativa, precisión y respeto por el oficio. Una sección viva. Aquí voy subiendo pruebas, notas y resultados con el tiempo. Si te mola esta parte del oficio (y no solo el resultado en foto), hablamos. Proyectos grandes = tiempo, cabeza y compromiso. “El oficio no es estética. Es método.” Lo visual importa, claro. Pero si no entiendes herramienta, piel, ritmo y curación, lo visual es humo. Aquí escribo para aprender, ordenar y compartir."
  },
  {
    "href": "/work",
    "title": "Work",
    "section": "work",
    "labels": [
      "work"
    ],
    "description": "Sección: Work.",
    "keywords": [
      "work"
    ],
    "excerpt": "Piezas publicadas: tattoo, arte, film, música, dev y journal. Todo vive en el mismo sistema. Sin carpetas mentales."
  },
];
